"""xoa 7 cot thua o nghi_phep (chuan bi gop giay_phep, quyet dinh khong gop nua)

Revision ID: b82fd132d140
Revises: 9a8f73c1f8b8
Create Date: 2026-08-30 23:02:42.790985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82fd132d140'
down_revision = '9a8f73c1f8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_nghiphep_chamcong'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_nghiphep_nguoiduyet'), type_='foreignkey')
        batch_op.drop_column('cham_cong_id')
        batch_op.drop_column('so_gio')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ngay_duyet')
        batch_op.drop_column('ly_do_tu_choi')
        batch_op.drop_column('nguoi_duyet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nguoi_duyet_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ly_do_tu_choi', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ngay_duyet', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('so_gio', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cham_cong_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_nghiphep_nguoiduyet'), 'nhan_vien', ['nguoi_duyet_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_nghiphep_chamcong'), 'cham_cong', ['cham_cong_id'], ['id'])

    # ### end Alembic commands ###
