"""bo sung cot updated_at con thieu o chi_tiet_luong

Revision ID: ff3a59eeb494
Revises: 97b7a4de6f28
Create Date: 2026-08-30 23:46:42.344137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3a59eeb494'
down_revision = '97b7a4de6f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
