"""enum hoa trang_thai/loai cho nghi_phep, giay_phep, bang_cap_chung_chi, nhan_vien

Revision ID: 4777b1a70f31
Revises: ff3a59eeb494
Create Date: 2026-09-01 22:30:56.688084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4777b1a70f31'
down_revision = 'ff3a59eeb494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bang_cap_chung_chi', schema=None) as batch_op:
        batch_op.alter_column('loai',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('certificate', 'degree', 'license', name='loai_chung_chi_enum'),
               existing_nullable=False)
        batch_op.alter_column('trang_thai',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('valid', 'expired', 'revoked', name='trang_thai_chung_chi_enum'),
               existing_nullable=True)

    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Đang chờ', 'Đã duyệt', 'Từ chối', name='trang_thai_giay_phep_enum'),
               existing_nullable=False)

    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Chờ duyệt', 'Đã duyệt', 'Từ chối', name='trang_thai_nghi_phep_enum'),
               existing_nullable=True)

    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Đang làm việc', 'Đã nghỉ việc', 'Tạm nghỉ', 'Thử việc', name='trang_thai_nhan_vien_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.Enum('Đang làm việc', 'Đã nghỉ việc', 'Tạm nghỉ', 'Thử việc', name='trang_thai_nhan_vien_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.Enum('Chờ duyệt', 'Đã duyệt', 'Từ chối', name='trang_thai_nghi_phep_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.Enum('Đang chờ', 'Đã duyệt', 'Từ chối', name='trang_thai_giay_phep_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('bang_cap_chung_chi', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.Enum('valid', 'expired', 'revoked', name='trang_thai_chung_chi_enum'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('loai',
               existing_type=sa.Enum('certificate', 'degree', 'license', name='loai_chung_chi_enum'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
