"""them soft-delete cho 13 bang nghiep vu con lai

Revision ID: 3ce34f81dc76
Revises: 2babcf8a544f
Create Date: 2026-08-30 23:23:45.384733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce34f81dc76'
down_revision = '2babcf8a544f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bang_cap_chung_chi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bang_cap_chung_chi_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('bang_luong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bang_luong_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('bh_dn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bh_dn_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cham_cong_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chi_tiet_luong_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_danh_gia_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_giay_phep_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('hopdong_laodong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hopdong_laodong_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('khautru_nhanvien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_khautru_nhanvien_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nghi_phep_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('nguoi_phu_thuoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nguoi_phu_thuoc_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('nhan_vien_phuc_loi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nhan_vien_phuc_loi_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('nhanvien_thuong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nhanvien_thuong_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhanvien_thuong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhanvien_thuong_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('nhan_vien_phuc_loi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phuc_loi_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('nguoi_phu_thuoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_phu_thuoc_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nghi_phep_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('khautru_nhanvien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_khautru_nhanvien_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('hopdong_laodong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hopdong_laodong_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giay_phep_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_luong_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cham_cong_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('bh_dn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bh_dn_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('bang_luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bang_luong_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('bang_cap_chung_chi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bang_cap_chung_chi_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
