"""them index cho FK con thieu va UniqueConstraint bang_luong

Revision ID: e14b414c0ada
Revises: b82fd132d140
Create Date: 2026-08-30 23:15:10.430852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14b414c0ada'
down_revision = 'b82fd132d140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bang_luong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bang_luong_nhan_vien_id'), ['nhan_vien_id'], unique=False)
        batch_op.create_unique_constraint('uq_bangluong_nv_ky', ['nhan_vien_id', 'thang', 'nam'])

    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cham_cong_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_luong_bang_luong_id'), ['bang_luong_id'], unique=False)

    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_gia_nguoi_danh_gia_id'), ['nguoi_danh_gia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giay_phep_cham_cong_id'), ['cham_cong_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giay_phep_nguoi_duyet_id'), ['nguoi_duyet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giay_phep_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('hopdong_laodong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hopdong_laodong_nhan_vien_id'), ['nhan_vien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hopdong_laodong_quyche_id'), ['quyche_id'], unique=False)

    with op.batch_alter_table('khautru_nhanvien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_khautru_nhanvien_khau_tru_id'), ['khau_tru_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_khautru_nhanvien_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('luong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luong_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nghi_phep_loai_nghi_phep_id'), ['loai_nghi_phep_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nghi_phep_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('nguoi_phu_thuoc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_phu_thuoc_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nhan_vien_chuc_vu_id'), ['chuc_vu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhan_vien_phong_ban_id'), ['phong_ban_id'], unique=False)

    with op.batch_alter_table('nhan_vien_phuc_loi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nhan_vien_phuc_loi_nhan_vien_id'), ['nhan_vien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhan_vien_phuc_loi_phuc_loi_id'), ['phuc_loi_id'], unique=False)

    with op.batch_alter_table('nhanvien_thuong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nhanvien_thuong_nhanvien_id'), ['nhanvien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhanvien_thuong_thuong_id'), ['thuong_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhanvien_thuong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhanvien_thuong_thuong_id'))
        batch_op.drop_index(batch_op.f('ix_nhanvien_thuong_nhanvien_id'))

    with op.batch_alter_table('nhan_vien_phuc_loi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phuc_loi_phuc_loi_id'))
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phuc_loi_nhan_vien_id'))

    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phong_ban_id'))
        batch_op.drop_index(batch_op.f('ix_nhan_vien_chuc_vu_id'))

    with op.batch_alter_table('nguoi_phu_thuoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_phu_thuoc_nhan_vien_id'))

    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nghi_phep_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_nghi_phep_loai_nghi_phep_id'))

    with op.batch_alter_table('luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luong_nhan_vien_id'))

    with op.batch_alter_table('khautru_nhanvien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_khautru_nhanvien_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_khautru_nhanvien_khau_tru_id'))

    with op.batch_alter_table('hopdong_laodong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hopdong_laodong_quyche_id'))
        batch_op.drop_index(batch_op.f('ix_hopdong_laodong_nhan_vien_id'))

    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giay_phep_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_giay_phep_nguoi_duyet_id'))
        batch_op.drop_index(batch_op.f('ix_giay_phep_cham_cong_id'))

    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_nguoi_danh_gia_id'))

    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_luong_bang_luong_id'))

    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cham_cong_nhan_vien_id'))

    with op.batch_alter_table('bang_luong', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bangluong_nv_ky', type_='unique')
        batch_op.drop_index(batch_op.f('ix_bang_luong_nhan_vien_id'))

    # ### end Alembic commands ###
