"""them soft-delete cho nhan_vien (mau tham chieu)

Revision ID: 2babcf8a544f
Revises: e14b414c0ada
Create Date: 2026-08-30 23:18:11.551152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2babcf8a544f'
down_revision = 'e14b414c0ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nhan_vien_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhan_vien_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
