"""them soft delete cho thuong khau_tru phuc_loi

Revision ID: 7e4e102f7eea
Revises: 380f4c9cfa57
Create Date: 2026-09-07 21:36:11.876577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4e102f7eea'
down_revision = '380f4c9cfa57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - đã dọn tay ###
    # Autogenerate lúc đầu còn kèm theo 1 loạt drop_constraint(type_='check')
    # cho các cột Enum ở nhiều bảng khác hoàn toàn không liên quan — do SQLite
    # (dùng để autogenerate migration này) phản ánh named CHECK constraint
    # khác Postgres (DB thật của project), Alembic tưởng nhầm là "bị xóa" dù
    # model không hề đổi (xem chú thích tương tự ở migration RBAC trước đó).
    # Đã bỏ toàn bộ phần đó, chỉ giữ đúng 3 thay đổi thật: thêm deleted_at +
    # deleted_by cho thuong/khau_tru/phuc_loi (bật SoftDeleteMixin).
    with op.batch_alter_table('khau_tru', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_khau_tru_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_khau_tru_deleted_by', 'nhan_vien', ['deleted_by'], ['id'])

    with op.batch_alter_table('phuc_loi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_phuc_loi_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_phuc_loi_deleted_by', 'nhan_vien', ['deleted_by'], ['id'])

    with op.batch_alter_table('thuong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_thuong_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_thuong_deleted_by', 'nhan_vien', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - đã dọn tay (xem ghi chú ở upgrade) ###
    with op.batch_alter_table('thuong', schema=None) as batch_op:
        batch_op.drop_constraint('fk_thuong_deleted_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_thuong_deleted_at'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('phuc_loi', schema=None) as batch_op:
        batch_op.drop_constraint('fk_phuc_loi_deleted_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_phuc_loi_deleted_at'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('khau_tru', schema=None) as batch_op:
        batch_op.drop_constraint('fk_khau_tru_deleted_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_khau_tru_deleted_at'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
    # ### end Alembic commands ###
