"""initial schema (squashed baseline - tao toan bo bang tu models hien tai)

Revision ID: c037d027ff73
Revises: 
Create Date: 2026-09-01 23:00:50.745201

"""
from alembic import op
import sqlalchemy as sa
import app.models.nhan_vien_model


# revision identifiers, used by Alembic.
revision = 'c037d027ff73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chuc_vu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_chuc_vu', sa.Integer(), nullable=True),
    sa.Column('ten_chuc_vu', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_chuc_vu')
    )
    op.create_table('khau_tru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_khau_tru', sa.String(length=255), nullable=False),
    sa.Column('loai_khau_tru', sa.Enum('UNG_LUONG', 'VI_PHAM', 'TRU_KHAC', name='loai_khau_tru_enum', create_constraint=True), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ghi_chu', sa.String(length=255), nullable=True),
    sa.Column('ngay_quyet_dinh', sa.Date(), nullable=False),
    sa.Column('file_dinh_kem', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loai_nghi_phep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=50), nullable=False),
    sa.Column('mo_ta', sa.String(length=200), nullable=True),
    sa.Column('co_luong', sa.Boolean(), nullable=True),
    sa.Column('don_vi_tinh', sa.Enum('NGAY', 'GIO', name='donvitinh', create_constraint=True), nullable=False),
    sa.Column('yeu_cau_cham_cong', sa.Boolean(), nullable=False),
    sa.Column('yeu_cau_thong_tin_sinh', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('ngay_nghi_le',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_ngay', sa.String(length=100), nullable=False),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=False),
    sa.Column('mo_ta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phong_ban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_phong_ban', sa.Integer(), nullable=False),
    sa.Column('ten_phong_ban', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_phong_ban')
    )
    op.create_table('phuc_loi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_phuc_loi', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('gia_tri', sa.Float(), nullable=True),
    sa.Column('loai', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quyche_congty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_quyche', sa.String(length=255), nullable=False),
    sa.Column('di_tre_phat', sa.Float(), nullable=False),
    sa.Column('ve_som_phat', sa.Float(), nullable=False),
    sa.Column('tang_ca_heso', sa.Float(), nullable=False),
    sa.Column('luong_ngay_le_heso', sa.Float(), nullable=False),
    sa.Column('luong_cuoi_tuan_heso', sa.Float(), nullable=False),
    sa.Column('phu_cap_an_trua', sa.Float(), nullable=False),
    sa.Column('phu_cap_xang_xe', sa.Float(), nullable=True),
    sa.Column('phu_cap_doc_hai', sa.Float(), nullable=False),
    sa.Column('phu_cap_trach_nhiem', sa.Float(), nullable=False),
    sa.Column('phu_cap_chuc_vu', sa.Float(), nullable=True),
    sa.Column('phu_cap_tham_nien', sa.Float(), nullable=True),
    sa.Column('quy_dinh_khac', sa.JSON(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thiet_bi_cham_cong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_thiet_bi', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('thoi_gian_tao', sa.DateTime(), nullable=True),
    sa.Column('lan_su_dung_cuoi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thiet_bi_cham_cong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thiet_bi_cham_cong_token_hash'), ['token_hash'], unique=True)

    op.create_table('thuong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_thuong', sa.String(length=255), nullable=False),
    sa.Column('loai_thuong', sa.String(length=100), nullable=True),
    sa.Column('so_tien', sa.Numeric(precision=18, scale=1), nullable=False),
    sa.Column('ngay_quyet_dinh', sa.Date(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhan_vien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('gioi_tinh', sa.String(length=10), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('dia_chi', sa.String(length=255), nullable=True),
    sa.Column('phong_ban_id', sa.Integer(), nullable=True),
    sa.Column('chuc_vu_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('trang_thai', sa.Enum('Đang làm việc', 'Đã nghỉ việc', 'Tạm nghỉ', 'Thử việc', name='trang_thai_nhan_vien_enum', create_constraint=True), nullable=True),
    sa.Column('so_ngay_phep_con_lai', sa.Integer(), nullable=True),
    sa.Column('face_encoding', app.models.nhan_vien_model.FaceEncodingType(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chuc_vu_id'], ['chuc_vu.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['phong_ban_id'], ['phong_ban.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('so_dien_thoai')
    )
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nhan_vien_chuc_vu_id'), ['chuc_vu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhan_vien_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhan_vien_phong_ban_id'), ['phong_ban_id'], unique=False)

    op.create_table('bang_cap_chung_chi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('loai', sa.Enum('certificate', 'degree', 'license', name='loai_chung_chi_enum', create_constraint=True), nullable=False),
    sa.Column('ten', sa.String(length=255), nullable=False),
    sa.Column('so_hieu', sa.String(length=100), nullable=True),
    sa.Column('to_chuc_cap', sa.String(length=255), nullable=True),
    sa.Column('ngay_cap', sa.Date(), nullable=True),
    sa.Column('ngay_het_han', sa.Date(), nullable=True),
    sa.Column('xep_loai', sa.String(length=50), nullable=True),
    sa.Column('diem_so', sa.String(length=50), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('tep_dinh_kem', sa.String(length=255), nullable=True),
    sa.Column('credential_id', sa.String(length=120), nullable=True),
    sa.Column('credential_url', sa.String(length=255), nullable=True),
    sa.Column('trang_thai', sa.Enum('valid', 'expired', 'revoked', name='trang_thai_chung_chi_enum', create_constraint=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bang_cap_chung_chi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bang_cap_chung_chi_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bang_cap_chung_chi_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('bang_luong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('ngay_cong_chuan', sa.Integer(), nullable=True),
    sa.Column('so_ngay_cong', sa.Integer(), nullable=True),
    sa.Column('nghi_phep', sa.Integer(), nullable=True),
    sa.Column('tong_ngay_lam_le', sa.Float(), nullable=True),
    sa.Column('tong_tien_lam_le', sa.Float(), nullable=True),
    sa.Column('tong_ngay_cuoi_tuan', sa.Float(), nullable=True),
    sa.Column('tong_tien_cuoi_tuan', sa.Float(), nullable=True),
    sa.Column('tong_gio_tang_ca', sa.Float(), nullable=True),
    sa.Column('tong_tien_tang_ca', sa.Float(), nullable=True),
    sa.Column('tong_khau_tru', sa.Float(), nullable=True),
    sa.Column('tong_phu_cap', sa.Float(), nullable=True),
    sa.Column('tong_thuong', sa.Float(), nullable=True),
    sa.Column('bhxh', sa.Float(), nullable=True),
    sa.Column('bhtn', sa.Float(), nullable=True),
    sa.Column('bhyt', sa.Float(), nullable=True),
    sa.Column('thue_tncn', sa.Float(), nullable=True),
    sa.Column('tong_luong', sa.Float(), nullable=True),
    sa.Column('thuc_nhan', sa.Float(), nullable=True),
    sa.Column('ghi_chu', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nhan_vien_id', 'thang', 'nam', name='uq_bangluong_nv_ky')
    )
    with op.batch_alter_table('bang_luong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bang_luong_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bang_luong_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('bh_dn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('bhxh_dn', sa.Float(), nullable=True),
    sa.Column('bhyt_dn', sa.Float(), nullable=True),
    sa.Column('bhtn_dn', sa.Float(), nullable=True),
    sa.Column('tong_bh_dn', sa.Float(), nullable=True),
    sa.Column('ghi_chu', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bh_dn', schema=None) as batch_op:
        batch_op.create_index('idx_bh_dn_nam', ['nam'], unique=False)
        batch_op.create_index('idx_bh_dn_nhan_vien', ['nhan_vien_id'], unique=False)
        batch_op.create_index('idx_bh_dn_thang_nam', ['thang', 'nam'], unique=False)
        batch_op.create_index(batch_op.f('ix_bh_dn_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('cham_cong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('thoi_gian_vao', sa.DateTime(), nullable=True),
    sa.Column('thoi_gian_ra', sa.DateTime(), nullable=True),
    sa.Column('ngay', sa.Date(), nullable=True),
    sa.Column('hinh_anh_vao', sa.String(length=255), nullable=True),
    sa.Column('hinh_anh_ra', sa.String(length=255), nullable=True),
    sa.Column('so_cong', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cham_cong_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cham_cong_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_danh_gia_id', sa.Integer(), nullable=False),
    sa.Column('ky_ngay', sa.Date(), nullable=False),
    sa.Column('ky_loai', sa.Enum('MONTH', 'QUARTER', 'YEAR', name='enum_ky_loai', create_constraint=True), nullable=False),
    sa.Column('diem_chuyen_can', sa.Float(), nullable=True),
    sa.Column('diem_hieu_qua', sa.Float(), nullable=True),
    sa.Column('diem_ky_nang', sa.Float(), nullable=True),
    sa.Column('diem_thai_do', sa.Float(), nullable=True),
    sa.Column('diem_chu_dong', sa.Float(), nullable=True),
    sa.Column('w_chuyen_can', sa.Float(), nullable=False),
    sa.Column('w_hieu_qua', sa.Float(), nullable=False),
    sa.Column('w_ky_nang', sa.Float(), nullable=False),
    sa.Column('w_thai_do', sa.Float(), nullable=False),
    sa.Column('w_chu_dong', sa.Float(), nullable=False),
    sa.Column('nhan_xet', sa.Text(), nullable=True),
    sa.Column('mc_chuyen_can_ref', sa.String(length=512), nullable=True),
    sa.Column('mc_hieu_qua_ref', sa.String(length=512), nullable=True),
    sa.Column('mc_ky_nang_ref', sa.String(length=512), nullable=True),
    sa.Column('mc_thai_do_ref', sa.String(length=512), nullable=True),
    sa.Column('mc_chu_dong_ref', sa.String(length=512), nullable=True),
    sa.Column('phuong_thuc', sa.Enum('SELF', 'MANAGER', 'PEER', '_360', name='enum_phuong_thuc', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('(diem_chuyen_can IS NULL OR (diem_chuyen_can BETWEEN 0 AND 10)) AND (diem_hieu_qua   IS NULL OR (diem_hieu_qua   BETWEEN 0 AND 10)) AND (diem_ky_nang    IS NULL OR (diem_ky_nang    BETWEEN 0 AND 10)) AND (diem_thai_do    IS NULL OR (diem_thai_do    BETWEEN 0 AND 10)) AND (diem_chu_dong   IS NULL OR (diem_chu_dong   BETWEEN 0 AND 10))', name='ck_danhgia_scores_range'),
    sa.CheckConstraint('(w_chuyen_can + w_hieu_qua + w_ky_nang + w_thai_do + w_chu_dong) BETWEEN 0.999 AND 1.001', name='ck_danhgia_weights_sum'),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nguoi_danh_gia_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nhan_vien_id', 'ky_ngay', 'ky_loai', name='uq_danhgia_nv_ky')
    )
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_gia_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_nguoi_danh_gia_id'), ['nguoi_danh_gia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('hopdong_laodong',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('quyche_id', sa.Integer(), nullable=True),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=True),
    sa.Column('thoi_gian_hop_dong', sa.String(length=50), nullable=True),
    sa.Column('loai_hop_dong', sa.String(length=50), nullable=False),
    sa.Column('muc_luong_co_ban', sa.Float(), nullable=False),
    sa.Column('di_tre_phat', sa.Float(), nullable=True),
    sa.Column('ve_som_phat', sa.Float(), nullable=True),
    sa.Column('tang_ca_heso', sa.Float(), nullable=True),
    sa.Column('luong_ngay_le_heso', sa.Float(), nullable=True),
    sa.Column('luong_cuoi_tuan_heso', sa.Float(), nullable=True),
    sa.Column('phu_cap_an_trua', sa.Float(), nullable=True),
    sa.Column('phu_cap_xang_xe', sa.Float(), nullable=True),
    sa.Column('phu_cap_doc_hai', sa.Float(), nullable=True),
    sa.Column('phu_cap_trach_nhiem', sa.Float(), nullable=True),
    sa.Column('phu_cap_chuc_vu', sa.Float(), nullable=True),
    sa.Column('phu_cap_tham_nien', sa.Float(), nullable=True),
    sa.Column('dieu_khoan_khac', sa.JSON(), nullable=True),
    sa.Column('phep_nam', sa.Integer(), nullable=True),
    sa.Column('trang_thai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['quyche_id'], ['quyche_congty.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hopdong_laodong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hopdong_laodong_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hopdong_laodong_nhan_vien_id'), ['nhan_vien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hopdong_laodong_quyche_id'), ['quyche_id'], unique=False)

    op.create_table('khautru_nhanvien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('khau_tru_id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('so_tien_thuc_te', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['khau_tru_id'], ['khau_tru.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('khautru_nhanvien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_khautru_nhanvien_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_khautru_nhanvien_khau_tru_id'), ['khau_tru_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_khautru_nhanvien_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('luong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('so_ngay_cong', sa.Integer(), nullable=True),
    sa.Column('phu_cap', sa.Float(), nullable=True),
    sa.Column('khau_tru', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luong_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('nghi_phep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('loai_nghi_phep_id', sa.Integer(), nullable=False),
    sa.Column('tu_ngay', sa.DateTime(), nullable=False),
    sa.Column('den_ngay', sa.DateTime(), nullable=False),
    sa.Column('ly_do', sa.String(length=200), nullable=True),
    sa.Column('trang_thai', sa.Enum('Chờ duyệt', 'Đã duyệt', 'Từ chối', name='trang_thai_nghi_phep_enum', create_constraint=True), nullable=True),
    sa.Column('so_ngay_nghi', sa.Integer(), nullable=False),
    sa.Column('ngay_du_kien_sinh', sa.Date(), nullable=True),
    sa.Column('so_con', sa.Integer(), nullable=True),
    sa.Column('phuong_phap_sinh', sa.String(length=50), nullable=True),
    sa.Column('can_cu_phap_ly_file', sa.String(length=255), nullable=True),
    sa.Column('file_bo_sung', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['loai_nghi_phep_id'], ['loai_nghi_phep.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nghi_phep_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nghi_phep_loai_nghi_phep_id'), ['loai_nghi_phep_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nghi_phep_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('nguoi_phu_thuoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('ho_ten', sa.String(length=255), nullable=False),
    sa.Column('quan_he', sa.String(length=100), nullable=False),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nguoi_phu_thuoc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_phu_thuoc_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nguoi_phu_thuoc_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    op.create_table('nhan_vien_phuc_loi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=True),
    sa.Column('phuc_loi_id', sa.Integer(), nullable=True),
    sa.Column('ngay_ap_dung', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['phuc_loi_id'], ['phuc_loi.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nhan_vien_phuc_loi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nhan_vien_phuc_loi_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhan_vien_phuc_loi_nhan_vien_id'), ['nhan_vien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhan_vien_phuc_loi_phuc_loi_id'), ['phuc_loi_id'], unique=False)

    op.create_table('nhanvien_thuong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhanvien_id', sa.Integer(), nullable=False),
    sa.Column('thuong_id', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.String(length=50), nullable=True),
    sa.Column('so_tien_thuc_te', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhanvien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['thuong_id'], ['thuong.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nhanvien_thuong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nhanvien_thuong_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhanvien_thuong_nhanvien_id'), ['nhanvien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nhanvien_thuong_thuong_id'), ['thuong_id'], unique=False)

    op.create_table('chi_tiet_luong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bang_luong_id', sa.Integer(), nullable=False),
    sa.Column('nhom', sa.Enum('KHAU_TRU', 'PHU_CAP', 'THUONG', name='nhomchitietluong', create_constraint=True), nullable=False),
    sa.Column('loai', sa.String(length=100), nullable=False),
    sa.Column('so_tien', sa.Float(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bang_luong_id'], ['bang_luong.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_luong_bang_luong_id'), ['bang_luong_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_luong_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('giay_phep',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nhan_vien_id', sa.Integer(), nullable=False),
    sa.Column('cham_cong_id', sa.Integer(), nullable=False),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=False),
    sa.Column('loai_giay_phep', sa.String(length=100), nullable=False),
    sa.Column('ly_do', sa.Text(), nullable=True),
    sa.Column('so_gio', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('Đang chờ', 'Đã duyệt', 'Từ chối', name='trang_thai_giay_phep_enum', create_constraint=True), nullable=False),
    sa.Column('nguoi_duyet_id', sa.Integer(), nullable=True),
    sa.Column('ngay_duyet', sa.DateTime(), nullable=True),
    sa.Column('ly_do_tu_choi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cham_cong_id'], ['cham_cong.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nguoi_duyet_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['nhan_vien_id'], ['nhan_vien.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['nhan_vien.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giay_phep_cham_cong_id'), ['cham_cong_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giay_phep_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_giay_phep_nguoi_duyet_id'), ['nguoi_duyet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giay_phep_nhan_vien_id'), ['nhan_vien_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giay_phep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giay_phep_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_giay_phep_nguoi_duyet_id'))
        batch_op.drop_index(batch_op.f('ix_giay_phep_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_giay_phep_cham_cong_id'))

    op.drop_table('giay_phep')
    with op.batch_alter_table('chi_tiet_luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_luong_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_luong_bang_luong_id'))

    op.drop_table('chi_tiet_luong')
    with op.batch_alter_table('nhanvien_thuong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhanvien_thuong_thuong_id'))
        batch_op.drop_index(batch_op.f('ix_nhanvien_thuong_nhanvien_id'))
        batch_op.drop_index(batch_op.f('ix_nhanvien_thuong_deleted_at'))

    op.drop_table('nhanvien_thuong')
    with op.batch_alter_table('nhan_vien_phuc_loi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phuc_loi_phuc_loi_id'))
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phuc_loi_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phuc_loi_deleted_at'))

    op.drop_table('nhan_vien_phuc_loi')
    with op.batch_alter_table('nguoi_phu_thuoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_phu_thuoc_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_nguoi_phu_thuoc_deleted_at'))

    op.drop_table('nguoi_phu_thuoc')
    with op.batch_alter_table('nghi_phep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nghi_phep_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_nghi_phep_loai_nghi_phep_id'))
        batch_op.drop_index(batch_op.f('ix_nghi_phep_deleted_at'))

    op.drop_table('nghi_phep')
    with op.batch_alter_table('luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luong_nhan_vien_id'))

    op.drop_table('luong')
    with op.batch_alter_table('khautru_nhanvien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_khautru_nhanvien_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_khautru_nhanvien_khau_tru_id'))
        batch_op.drop_index(batch_op.f('ix_khautru_nhanvien_deleted_at'))

    op.drop_table('khautru_nhanvien')
    with op.batch_alter_table('hopdong_laodong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hopdong_laodong_quyche_id'))
        batch_op.drop_index(batch_op.f('ix_hopdong_laodong_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_hopdong_laodong_deleted_at'))

    op.drop_table('hopdong_laodong')
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_nguoi_danh_gia_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_deleted_at'))

    op.drop_table('danh_gia')
    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cham_cong_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_cham_cong_deleted_at'))

    op.drop_table('cham_cong')
    with op.batch_alter_table('bh_dn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bh_dn_deleted_at'))
        batch_op.drop_index('idx_bh_dn_thang_nam')
        batch_op.drop_index('idx_bh_dn_nhan_vien')
        batch_op.drop_index('idx_bh_dn_nam')

    op.drop_table('bh_dn')
    with op.batch_alter_table('bang_luong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bang_luong_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_bang_luong_deleted_at'))

    op.drop_table('bang_luong')
    with op.batch_alter_table('bang_cap_chung_chi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bang_cap_chung_chi_nhan_vien_id'))
        batch_op.drop_index(batch_op.f('ix_bang_cap_chung_chi_deleted_at'))

    op.drop_table('bang_cap_chung_chi')
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nhan_vien_phong_ban_id'))
        batch_op.drop_index(batch_op.f('ix_nhan_vien_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_nhan_vien_chuc_vu_id'))

    op.drop_table('nhan_vien')
    op.drop_table('thuong')
    with op.batch_alter_table('thiet_bi_cham_cong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thiet_bi_cham_cong_token_hash'))

    op.drop_table('thiet_bi_cham_cong')
    op.drop_table('quyche_congty')
    op.drop_table('phuc_loi')
    op.drop_table('phong_ban')
    op.drop_table('ngay_nghi_le')
    op.drop_table('loai_nghi_phep')
    op.drop_table('khau_tru')
    op.drop_table('chuc_vu')
    # ### end Alembic commands ###
