"""them vai tro va quyen (RBAC)

Revision ID: 380f4c9cfa57
Revises: c037d027ff73
Create Date: 2026-09-04 11:08:43.802451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380f4c9cfa57'
down_revision = 'c037d027ff73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - đã dọn tay ###
    # Autogenerate lúc đầu còn kèm theo 1 loạt drop_constraint(type_='check') cho
    # các cột Enum ở nhiều bảng khác hoàn toàn không liên quan (bang_cap_chung_chi,
    # chi_tiet_luong, danh_gia, giay_phep, khau_tru, loai_nghi_phep, nghi_phep,
    # nhan_vien.trang_thai) — đây là do SQLite (dùng để autogenerate migration này)
    # phản ánh named CHECK constraint khác Postgres (DB thật của project), Alembic
    # tưởng nhầm là "bị xóa" dù model không hề đổi. Đã bỏ toàn bộ phần đó, chỉ giữ
    # lại đúng thay đổi thật: 3 bảng mới cho RBAC + cột vai_tro_id.
    op.create_table('quyen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_quyen', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('hanh_dong', sa.Enum('xem', 'them', 'sua', 'xoa', name='hanh_dong_quyen_enum', create_constraint=True), nullable=False),
    sa.Column('mo_ta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_quyen')
    )
    op.create_table('vai_tro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_vai_tro', sa.String(length=100), nullable=False),
    sa.Column('mo_ta', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_vai_tro')
    )
    op.create_table('vai_tro_quyen',
    sa.Column('vai_tro_id', sa.Integer(), nullable=False),
    sa.Column('quyen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quyen_id'], ['quyen.id'], ),
    sa.ForeignKeyConstraint(['vai_tro_id'], ['vai_tro.id'], ),
    sa.PrimaryKeyConstraint('vai_tro_id', 'quyen_id')
    )
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vai_tro_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nhan_vien_vai_tro_id'), ['vai_tro_id'], unique=False)
        batch_op.create_foreign_key('fk_nhan_vien_vai_tro_id', 'vai_tro', ['vai_tro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - đã dọn tay (xem ghi chú ở upgrade) ###
    with op.batch_alter_table('nhan_vien', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nhan_vien_vai_tro_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_nhan_vien_vai_tro_id'))
        batch_op.drop_column('vai_tro_id')

    op.drop_table('vai_tro_quyen')
    op.drop_table('vai_tro')
    op.drop_table('quyen')
    # ### end Alembic commands ###

    # op.drop_table('quyen') không tự xóa TYPE Postgres gắn với cột hanh_dong
    # (sa.Enum tạo hẳn 1 native TYPE riêng trên Postgres, không giống SQLite).
    # Thiếu dòng này thì downgrade xong upgrade lại sẽ lỗi "type already
    # exists" trên Postgres — SQLite không phát hiện ra vì không có khái niệm
    # TYPE riêng nên round-trip vẫn "sạch" dù thiếu bước này.
    sa.Enum(name='hanh_dong_quyen_enum').drop(op.get_bind(), checkfirst=True)
